// =====================================================================================================================
// rdpp.cpp - Generated by Code_Parser_Cpp - Create Recursive Descent Predictive Parser on 2015-08-01 00:03:39 for C++14
// =====================================================================================================================
#pragma once
#include "skoarcery.hpp"
#include "noad_fwd.hpp"
#include "toker.hpp"

class SkoarParser {
public:
    void fail();
    void fail_too_deep();

    SkoarToker *toker;
    int deep;
    map<string, list<SkoarToke*>> desirables;
             SkoarParser(SkoarToker * toker);
    void init_desirables();
    SkoarNoad* listy(SkoarNoad* parent);
    SkoarNoad* cthulhu(SkoarNoad* parent);
    SkoarNoad* loop_condition(SkoarNoad* parent);
    SkoarNoad* ottavas(SkoarNoad* parent);
    SkoarNoad* pedally(SkoarNoad* parent);
    SkoarNoad* deref_prime(SkoarNoad* parent);
    SkoarNoad* dynamic(SkoarNoad* parent);
    SkoarNoad* args_entries(SkoarNoad* parent);
    SkoarNoad* assignment(SkoarNoad* parent);
    SkoarNoad* msgable(SkoarNoad* parent);
    SkoarNoad* branch(SkoarNoad* parent);
    SkoarNoad* listy_entries(SkoarNoad* parent);
    SkoarNoad* skrp_moar_lines(SkoarNoad* parent);
    SkoarNoad* phrasey(SkoarNoad* parent);
    SkoarNoad* deref(SkoarNoad* parent);
    SkoarNoad* moar_listy_entries(SkoarNoad* parent);
    SkoarNoad* beat(SkoarNoad* parent);
    SkoarNoad* args(SkoarNoad* parent);
    SkoarNoad* cond_ifs_suffix(SkoarNoad* parent);
    SkoarNoad* loop(SkoarNoad* parent);
    SkoarNoad* coda(SkoarNoad* parent);
    SkoarNoad* expr(SkoarNoad* parent);
    SkoarNoad* al_x(SkoarNoad* parent);
    SkoarNoad* optional_voice(SkoarNoad* parent);
    SkoarNoad* marker(SkoarNoad* parent);
    SkoarNoad* skrp_sig(SkoarNoad* parent);
    SkoarNoad* listy_suffix(SkoarNoad* parent);
    SkoarNoad* math(SkoarNoad* parent);
    SkoarNoad* cond_ifs(SkoarNoad* parent);
    SkoarNoad* skoarpion(SkoarNoad* parent);
    SkoarNoad* cthulhu_prime(SkoarNoad* parent);
    SkoarNoad* skrp_suffix(SkoarNoad* parent);
    SkoarNoad* branches(SkoarNoad* parent);
    SkoarNoad* dal_goto(SkoarNoad* parent);
    SkoarNoad* musical_keyword_misc(SkoarNoad* parent);
    SkoarNoad* skoar(SkoarNoad* parent);
    SkoarNoad* cond_if(SkoarNoad* parent);
    SkoarNoad* optional_args(SkoarNoad* parent);
    SkoarNoad* if_body(SkoarNoad* parent);
    SkoarNoad* settable(SkoarNoad* parent);
    SkoarNoad* phrases(SkoarNoad* parent);
    SkoarNoad* musical_keyword(SkoarNoad* parent);
    SkoarNoad* args_suffix(SkoarNoad* parent);
    SkoarNoad* msg(SkoarNoad* parent);
    SkoarNoad* nouny(SkoarNoad* parent);
    SkoarNoad* expr_prime(SkoarNoad* parent);
    SkoarNoad* cond_else(SkoarNoad* parent);
    SkoarNoad* loop_body(SkoarNoad* parent);
    SkoarNoad* moar_args_entries(SkoarNoad* parent);
    SkoarNoad* boolean(SkoarNoad* parent);
    SkoarNoad* skrp_sep_or_nl(SkoarNoad* parent);
    SkoarNoad* msg_chain_node(SkoarNoad* parent);
    SkoarNoad* conditional(SkoarNoad* parent);
    SkoarNoad* nouny_literal(SkoarNoad* parent);
    SkoarNoad* skrp_lines(SkoarNoad* parent);
    SkoarNoad* optional_al_coda(SkoarNoad* parent);
};

