# ===========================================================================
# lex.py - Generated by Code_Py_Lexer on 2015-08-06 00:08:53 for Python 3.3.2
# ===========================================================================

import re
import abc


class SubclassResponsibilityError(NotImplementedError):
    pass


class SkoarError(AssertionError):
    pass


